# -*- coding: utf-8 -*-
"""server

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qoy9IPHcvLHR-cQ7L-MJw24yU0GyRvU1
"""

from flask import Flask, request, render_template
import cv2
import numpy as np

app = Flask(__name__)

@app.route("/", methods=["GET", "POST"])
def index():
    if request.method == "POST":
        file = request.files["file"]
        if file:
            img = cv2.imdecode(np.frombuffer(file.read(), np.uint8), cv2.IMREAD_COLOR)
            result = process_image(img)
            return render_template("index.html", result=result)
    return render_template("index.html")

def process_image(image):
    # Dummy processing function
    return "Healthy Crop Detected"

if __name__ == "__main__":
    app.run(debug=True)